import type { Metadata } from 'next';
import { Geist_Mono, Manrope } from 'next/font/google';
import './globals.css';
import 'sileo/styles.css';
import 'ldrs/react/Tailspin.css';
import { AppProviders } from '@/components/providers/AppProviders';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  weight: 'variable',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'icsacv app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${manrope.variable} ${geistMono.variable}`}
      lang="es"
      suppressHydrationWarning
    >
      <body className={`${manrope.className} antialiased`} suppressHydrationWarning>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
